# Generated by Django 6.0.5 on 2026-05-20 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número Identificador')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Canción')),
                ('artista', models.CharField(max_length=255, verbose_name='Artista')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de Publicación')),
                ('archivo_mp4', models.FileField(upload_to='canciones/videos/', verbose_name='Archivo MP4 (Video/Audio)')),
                ('imagen', models.ImageField(upload_to='canciones/portadas/', verbose_name='Imagen de Portada')),
            ],
        ),
        migrations.CreateModel(
            name='BingoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='current_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_song', to='bingo.song'),
        ),
        migrations.CreateModel(
            name='BingoCardSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.bingocard')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.song')),
            ],
        ),
    ]
