# Generated by Django 6.0.5 on 2026-06-01 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_size', models.IntegerField(default=15)),
                ('chat_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número Identificador')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Canción')),
                ('artista', models.CharField(max_length=255, verbose_name='Artista')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de Publicación')),
                ('en_juego', models.BooleanField(db_index=True, default=True)),
                ('archivo_mp4', models.FileField(blank=True, null=True, upload_to='canciones/videos/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='canciones/portadas/')),
            ],
        ),
        migrations.CreateModel(
            name='BingoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bingo_cards', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='bingo.game')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bingo.game')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bingo.game')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.song')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='current_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in_games', to='bingo.song'),
        ),
        migrations.CreateModel(
            name='BingoCardSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked', models.BooleanField(db_index=True, default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='bingo.bingocard')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.song')),
            ],
        ),
    ]
