# Generated by Django 6.0.5 on 2026-05-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='archivo_mp4',
            field=models.FileField(blank=True, null=True, upload_to='canciones/videos/', verbose_name='Archivo MP4 (Video/Audio)'),
        ),
        migrations.AlterField(
            model_name='song',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='canciones/portadas/', verbose_name='Imagen de Portada'),
        ),
    ]
