# Generated by Django 6.0.5 on 2026-06-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='total_songs_limit',
            field=models.IntegerField(default=90, help_text='Total de canciones para esta partida'),
        ),
        migrations.AlterField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
