# Generated by Django 6.0.5 on 2026-06-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_game_total_songs_limit_alter_game_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='songs_in_game',
            field=models.ManyToManyField(related_name='games_included', to='bingo.song'),
        ),
        migrations.AlterField(
            model_name='game',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
