# Generated by Django 6.0.5 on 2026-05-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_alter_song_archivo_mp4_alter_song_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='en_juego',
            field=models.BooleanField(default=True, verbose_name='¿Disponible para esta partida?'),
        ),
    ]
