# Generated by Django 6.0.5 on 2026-07-04 16:38

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_game_songs_in_game_alter_game_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bingocard',
            options={'verbose_name': 'Carton de bingo', 'verbose_name_plural': 'Cartones de bingo'},
        ),
        migrations.AlterModelOptions(
            name='bingocardsong',
            options={'verbose_name': 'Cancion en carton', 'verbose_name_plural': 'Canciones en cartones'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'Mensaje de chat', 'verbose_name_plural': 'Mensajes de chat'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
        migrations.AlterModelOptions(
            name='gamehistory',
            options={'ordering': ['-played_at'], 'verbose_name': 'Historial de cancion', 'verbose_name_plural': 'Historial de canciones'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['numero'], 'verbose_name': 'Cancion', 'verbose_name_plural': 'Canciones'},
        ),
        migrations.AlterField(
            model_name='bingocard',
            name='codigo',
            field=models.CharField(default='', max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='card_size',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Tamano del carton'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre de la sala'),
        ),
        migrations.AlterField(
            model_name='game',
            name='songs_in_game',
            field=models.ManyToManyField(blank=True, related_name='games_included', to='bingo.song'),
        ),
        migrations.AlterField(
            model_name='game',
            name='total_songs_limit',
            field=models.IntegerField(default=90, help_text='Total de canciones para esta partida', validators=[django.core.validators.MinValueValidator(10)], verbose_name='Limite de canciones'),
        ),
        migrations.AlterField(
            model_name='song',
            name='fecha_publicacion',
            field=models.DateField(verbose_name='Fecha de Publicacion'),
        ),
        migrations.AlterField(
            model_name='song',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre de la Cancion'),
        ),
        migrations.AlterField(
            model_name='song',
            name='numero',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Numero Identificador'),
        ),
        migrations.AddIndex(
            model_name='bingocardsong',
            index=models.Index(fields=['card', 'marked'], name='idx_bingocardson_card_marked'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['game', 'timestamp'], name='idx_chat_game_timestamp'),
        ),
        migrations.AddIndex(
            model_name='gamehistory',
            index=models.Index(fields=['game', '-played_at'], name='idx_history_game_played'),
        ),
        migrations.AddConstraint(
            model_name='bingocard',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='unique_carton_por_usuario_y_partida'),
        ),
        migrations.AddConstraint(
            model_name='bingocardsong',
            constraint=models.UniqueConstraint(fields=('card', 'song'), name='unique_cancion_por_carton'),
        ),
    ]
