# Generated by Django 6.0.5 on 2026-05-23 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_song_en_juego'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bingo.game')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.song')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
    ]
