# Generated by Django 5.2.3 on 2026-05-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_gamehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='card_size',
            field=models.IntegerField(default=15),
        ),
    ]
